- name: Enroll new cert
  hosts: routers
  connection: local
  gather_facts: no
  vars_prompt:
  - name: "ansible_user"
    prompt: "Username"
    private: no
  - name: "ansible_ssh_pass"
    prompt: "Password"

  tasks:

  - include: tasks/gatherhostname.yaml
  - include: tasks/addcacert.yaml
  - include: tasks/enrollnewcert.yaml
  

